import type { Lang } from "./api";

export const STRINGS: Record<Lang, Record<string, string>> = {
  en: {
    brand: "Revenue Intelligence",
    navChat: "Chat Assistant",
    navCsv: "CSV Analyzer",
    navKpi: "KPI Calculator",
    chatHeader: "Revenue Analyst AI Assistant",
    chatPlaceholder: "Ask a question about SaaS metrics...",
    csvHeader: "CSV Revenue Analyzer",
    csvUploader: "Upload your sales CSV",
    csvPreview: "Data Preview",
    csvPlaceholder: "Ask about the data...",
    kpiHeader: "SaaS KPI Calculator",
    kpiCaption: "Pick a metric, fill in the inputs, and get the calculation plus benchmark context.",
    kpiMetricLabel: "Metric",
    kpiCalcButton: "Calculate",
    kpiBenchmark: "Benchmark context",
    sources: "Sources",
    noSources: "No sources retrieved.",
    send: "Send",
    thinking: "Thinking...",
    analyzing: "Analyzing...",
  },
  uk: {
    brand: "Revenue Intelligence",
    navChat: "Чат-асистент",
    navCsv: "Аналіз CSV",
    navKpi: "KPI-калькулятор",
    chatHeader: "AI-асистент з аналізу виручки",
    chatPlaceholder: "Постав питання про SaaS-метрики...",
    csvHeader: "Аналізатор CSV з даними про виручку",
    csvUploader: "Завантаж свій CSV з продажами",
    csvPreview: "Попередній перегляд даних",
    csvPlaceholder: "Постав питання про ці дані...",
    kpiHeader: "Калькулятор SaaS KPI",
    kpiCaption: "Обери метрику, заповни поля — отримаєш розрахунок і контекст бенчмарку.",
    kpiMetricLabel: "Метрика",
    kpiCalcButton: "Розрахувати",
    kpiBenchmark: "Контекст бенчмарку",
    sources: "Джерела",
    noSources: "Джерела не знайдено.",
    send: "Надіслати",
    thinking: "Думаю...",
    analyzing: "Аналізую...",
  },
};

export const KPI_LABELS: Record<Lang, Record<string, [string, string][]>> = {
  en: {
    mrr: [["value_a", "Sum of monthly recurring fees"]],
    arr: [["value_a", "MRR"]],
    cac: [["value_a", "Sales & marketing cost"], ["value_b", "New customers"]],
    ltv: [
      ["value_a", "ARPU"],
      ["value_b", "Monthly churn rate (0-1)"],
      ["value_c", "Gross margin % (0-1, default 0.8)"],
    ],
    churn: [["value_a", "Lost customers / churned MRR"], ["value_b", "Starting customers / starting MRR"]],
    nrr: [["value_a", "Ending ARR of starting cohort"], ["value_b", "Beginning ARR of starting cohort"]],
    grr: [["value_a", "Retained ARR before expansion"], ["value_b", "Beginning ARR"]],
    payback: [
      ["value_a", "CAC"],
      ["value_b", "ARPU"],
      ["value_c", "Gross margin % (0-1, default 0.8)"],
    ],
    arpu: [["value_a", "Total MRR"], ["value_b", "Active customers"]],
    ltv_cac: [["value_a", "LTV"], ["value_b", "CAC"]],
  },
  uk: {
    mrr: [["value_a", "Сума щомісячних повторюваних платежів"]],
    arr: [["value_a", "MRR"]],
    cac: [["value_a", "Витрати на продажі й маркетинг"], ["value_b", "Нові клієнти"]],
    ltv: [
      ["value_a", "ARPU"],
      ["value_b", "Місячний churn rate (0-1)"],
      ["value_c", "Валова маржа % (0-1, за замовч. 0.8)"],
    ],
    churn: [["value_a", "Втрачені клієнти / втрачений MRR"], ["value_b", "Клієнти / MRR на старт періоду"]],
    nrr: [["value_a", "Кінцевий ARR початкової когорти"], ["value_b", "Початковий ARR когорти"]],
    grr: [["value_a", "Утриманий ARR до expansion"], ["value_b", "Початковий ARR"]],
    payback: [
      ["value_a", "CAC"],
      ["value_b", "ARPU"],
      ["value_c", "Валова маржа % (0-1, за замовч. 0.8)"],
    ],
    arpu: [["value_a", "Загальний MRR"], ["value_b", "Активні клієнти"]],
    ltv_cac: [["value_a", "LTV"], ["value_b", "CAC"]],
  },
};
